// const assestPrefix = (process.env.NODE_ENV === "development") ? "" : "/demo/buzz-blitz";
const assestPrefix = ".";
// const assestPrefix = "/demo/buzz-blitz";
export const Images = {
  dark_eye_icon: "./icons/darkEyeIcon.png",
  light_eye_icon: "./icons/lightEyeIcon.png",
  lock_icon: "./icons/lockIcon.png",
  logout_icon: "./icons/logout_icon.png",
  new_logo: "./image/newLogo.png",
  next_icon: "./icons/NextIcon.png",
  person_icon: "./icons/PersonIcon.png",
  profile_image: "/image/profile_image.png",
  close_modal_icon: "/icons/close_modal_icon.png",
  successful_password_modal_img: "/image/successful_password_modal_img.png",
  login_icon: "./image/LoginInear.png",
  bg_Img: "./image/LoginBg.png",
  facebook_icon: "./image/facebook.png",
  google_icon: "./image/google.png",
  default_profile_avatar: "./image/default_profile_avatar.png",
  product_image: "./image/product_image.png",
  product_logo: "./image/product_logo.png",
  profile_photo_image: "./image/profile_photo_image.png",
  location_icon: "./icons/location_icon.png",
  chat_icon: "./icons/chat_icon.png",
  star_icon: "./icons/star_icon.png",
  brand_icon: "./icons/brand_icon.png",
  bookmark_icon: "./icons/bookmark_icon.png",
  share_icon: "./icons/share_icon.png",
  share_link_icon: "./icons/share_link_icon.png",
  whatsapp_icon: "./icons/whatsapp_icon.png",
  twitter_icon: "./icons/twitter_icon.png",
  selected_bookmark_icon: "./icons/selected_bookmark_icon.png",
  vertical_line_icon: "./icons/vertical_line_icon.png",
  bottom_border_icon: "./icons/bottom_border_icon.png",
  right_arrow_icon: "./icons/right_arrow_icon.png",
  uncolored_star_icon: "./icons/uncoloured_start_icon.png",
  colored_star_icon: "./icons/coloured_star_icon.png",
  email_icon: "./image/email_icon.png",
  phone_icon: "./image/phone_icon.png",
  order_product_image: "./image/order_product_image.png",
  pebea: "./image/pebea.png",
  back_button_icon: "./icons/back_button_icon.png",
  location_pin: "/icons/location_pin.png",
  rating_icon: "/icons/rating_icon.png",
  group_chat_icon: "/icons/group_chat_icon.png",
  product_image_three: "/image/product_image_three.png",
  icon_person: "/icons/icon_person.png",
  icon_location: "/icons/icon_location.png",
  icon_reciever: "/icons/icon_reciever.png",
  dash_line_cart: "/image/dash_line_cart.png",
  search_image_notfound: "/image/search_image_notfound.png",
  dropdown_icon: "/icons/dropdown_icon.png",
  select_icon: "/icons/select_icon.png",
  dropdown_icon_down: "/icons/dropdown_icon_down.png",
  pebea_icon: "./image/pebea.png",
  cart_image: "./image/cart_image.png",
  dash_line: "./image/dash_line.png",
  delete_cart_icon: "./icons/delete_cart_icon.png",
  coupon_icon: "./icons/coupon_icon.png",
  minus_icon: "./icons/minus_icon.png",
  add_icon: "./icons/add_icon.png",
  carousel_image: "./image/carouselImage.png",
  gallery_item: "./image/GalleryItem.png",
  vector: "./image/Vector.png",
  logo: "./image/logo.png",
  chat: "./icons/chat.svg",
  down_arrow: "./icons/downArrow.png",
  notification_icon: "./icons/bell.svg",
  pic: "./icons/pic.png",
  tiptop: "./icons/Vector.svg",
  shop_icon: "./icons/shore.svg",
  menu_icon: "./icons/menuIcon.png",
  logo_blue: "./image/logoBlue.png",
  instagram_icon: "./image/instagram.png",
  page_logo: "./image/Group.png",
  facebook_logo: "./image/facebook.png",
  twitter_logo: "./image/twitter.png",
  shirt_icon: "./image/Tshirt.png",
  apparel_icon: "./image/ApparelCategories.png",
  searchNoDataFound: "./image/searchNoDataFound.png",
  box_icon: "./image/boxs.png",
  sort_icon: "./image/sort.png",
  youtube_icon: "./icons/youtube.png",
  video_icon: "./icons/video_icon.png",
  logo_highpolar: "./image/logo-name.png",
  logo_highpolar_white: "./image/logo-name-white.png",
  hero_who_we_are: "./image/image.svg",
  banner: "./image/banner.webp",
  mantine: {
    hero_bullets: "./image/hero-bullets.svg",
    faq_image: "./image/faq.svg",
  },
  productDrop: {
    sale_banner: "./image/sale-banner.webp",
    shoe_green: "./image/shoe-green.webp",
    shoe_red: "./image/shoe-red.webp",
  },
  template9: {
    hero_banner: assestPrefix + "/image/temp9_assets/asset_1.webp",
    banner_hero_image: assestPrefix + "/image/temp9_assets/banner_hero.webp",
    banner_hero_image_light: assestPrefix + "/image/temp9_assets/banner_hero_light.webp",
    mobile_lcp_image: assestPrefix + "/image/temp9_assets/mobile_lcp.webp",
    temp_9_logo: assestPrefix + "/image/temp9_Assets/asset_19.svg",
    working: {
      img1: assestPrefix + "/image/temp9_assets/asset_3.webp",
      img2: assestPrefix + "/image/temp9_assets/asset_5.webp"
    },
    testimonial: {
      avatarSrc: assestPrefix + "/image/temp9_assets/asset_7.webp"
    },
    teams: {
      img1: assestPrefix + '/image/temp9_assets/asset_9.webp',
      img2: assestPrefix + '/image/temp9_assets/asset_10.webp',
      img3: assestPrefix + '/image/temp9_assets/asset_11.webp',
      img4: assestPrefix + '/image/temp9_assets/asset_12.webp',

    },
    pricing: {
      img1: assestPrefix + '/image/temp9_assets/asset_14.webp',
      img2: assestPrefix + '/image/temp9_assets/asset_15.webp',
      img3: assestPrefix + '/image/temp9_assets/asset_16.webp',
    },
    bodyCards: {
      img1: assestPrefix + '/image/temp9_assets/asset_17.webp',
      img2: assestPrefix + '/image/temp9_assets/asset_18.webp',
    },
    footer: {
      img1: assestPrefix + "/image/temp9_assets/asset_22.svg",
      img2: assestPrefix + "/image/temp9_assets/asset_23.svg",
      img3: assestPrefix + "/image/temp9_assets/asset_24.svg",
      img4: assestPrefix + "/image/temp9_assets/asset_25.svg",
      img5: assestPrefix + "/image/temp9_assets/asset_26.svg",
      img6: assestPrefix + "/image/temp9_assets/asset_27.svg",
    }

  }
}

